apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: bindings.azure.storagequeues
  version: v1
  metadata:
  - name: storageAccount
    value: 'mantasintrospect1stdapr2'
  - name: storageAccessKey
    value: '2OQq8d23YNrcoxaIsTkQRNdJefDGQGSOj8uUPf8ZdBEKn437U10r1XP0ryzl1q+aBHtJK2SGuR2o+AStmbOoVg=='
  - name: queue
    value: 'dapr-queue'
  - name: ttlInSeconds
    value: '120'

